using Bannister.Models;
using Bannister.Services;

namespace Bannister.Views;

public class VideoGenExperimentPage : ContentPage
{
    private readonly VideoGenExperimentService _service;
    private readonly AuthService _auth;
    private VerticalStackLayout _body = null!;
    private int _tab;
    private int? _week;
    private int? _expandedMethod;
    private double _threshold = 50;
    private readonly Dictionary<int, int> _executionStages = new();

    public VideoGenExperimentPage(VideoGenExperimentService service, AuthService auth)
    { _service = service; _auth = auth; Title = "Video Generation Experiments"; BackgroundColor = Color.FromArgb("#F5F5F5"); BuildUI(); }
    protected override async void OnAppearing() { base.OnAppearing(); await RefreshAsync(); }
    private void BuildUI()
    {
        var root = new VerticalStackLayout { Padding = 16, Spacing = 10 };
        root.Children.Add(new Label { Text = "Video Generation Experiments", FontSize = 24, FontAttributes = FontAttributes.Bold });
        var tabs = new HorizontalStackLayout { Spacing = 5 }; var names = new[] { "Weekly Methods", "Clips", "Stats", "Methods", "Execution" };
        for (var i = 0; i < names.Length; i++) { var index = i; var button = new Button { Text = names[i], FontSize = 11, Padding = new Thickness(8, 0) }; button.Clicked += async (_, _) => { _tab = index; await RefreshAsync(); }; tabs.Children.Add(button); }
        root.Children.Add(tabs); _body = new VerticalStackLayout { Spacing = 10 }; root.Children.Add(new ScrollView { Content = _body }); Content = root;
    }
    private async Task RefreshAsync() { _body.Children.Clear(); if (_tab == 0) await BuildWeeksAsync(); else if (_tab == 1) await BuildClipsAsync(); else if (_tab == 2) await BuildStatsAsync(); else if (_tab == 3) await BuildMethodsAsync(); else await BuildExecutionAsync(); }

    private async Task BuildWeeksAsync()
    {
        var username = _auth.CurrentUsername; var weeks = await _service.GetActiveWeeklyMethodsAsync(username); var methods = await _service.GetMethodsAsync(username);
        foreach (var week in weeks)
        {
            var clips = await _service.GetClipsAsync(username, week.Id); var stats = await _service.GetComparisonStatsAsync(username, week.Id); var method = week.MethodId.HasValue ? methods.FirstOrDefault(x => x.Id == week.MethodId.Value) : null; var stack = new VerticalStackLayout { Spacing = 5 };
            stack.Children.Add(new Label { Text = week.WeekLabel, FontSize = 18, FontAttributes = FontAttributes.Bold }); stack.Children.Add(new Label { Text = week.MethodDescription, MaxLines = 3 }); stack.Children.Add(new Label { Text = $"{clips.Count} clips · {clips.Count(x => x.PostedDate.HasValue)} posted · Avg {stats.AverageRetention10s:0.#}/{stats.AverageRetention20s:0.#}/{stats.AverageRetention30s:0.#}" });
            if (method != null) { stack.Children.Add(new Label { Text = $"Method: {method.Name} v{method.Version}", TextColor = Color.FromArgb("#1565C0") }); var view = new Button { Text = "View Method", FontSize = 12 }; view.Clicked += async (_, _) => await ShowSnapshotAsync(week.Id, method.Name); stack.Children.Add(view); }
            var buttons = new HorizontalStackLayout { Spacing = 6 }; var open = new Button { Text = "View Clips" }; open.Clicked += async (_, _) => { _week = week.Id; _tab = 1; await RefreshAsync(); }; var archive = new Button { Text = "Archive" }; archive.Clicked += async (_, _) => { await _service.ArchiveWeeklyMethodAsync(week.Id); await RefreshAsync(); }; buttons.Children.Add(open); buttons.Children.Add(archive); stack.Children.Add(buttons); _body.Children.Add(new Frame { Padding = 12, BackgroundColor = Colors.White, Content = stack });
        }
        _body.Children.Add(new Label { Text = "Add Week", FontSize = 20, FontAttributes = FontAttributes.Bold }); var start = new DatePicker { Date = DateTime.Today }; var end = new DatePicker { Date = DateTime.Today.AddDays(6) }; _body.Children.Add(new Label { Text = "Week start", FontSize = 12 }); _body.Children.Add(start); _body.Children.Add(new Label { Text = "Week end", FontSize = 12 }); _body.Children.Add(end);
        var methodPicker = new Picker { Title = "Method (optional)", ItemsSource = new[] { "None / Free form" }.Concat(methods.Select(x => $"{x.Name} v{x.Version}")).ToList(), SelectedIndex = 0 }; var description = new Editor { Placeholder = "Describe the production method...", HeightRequest = 110 }; var save = new Button { Text = "Save Week" };
        save.Clicked += async (_, _) => { var selected = methodPicker.SelectedIndex > 0 ? methods[methodPicker.SelectedIndex - 1] : null; var item = new WeeklyMethodExperiment { Username = username, WeekLabel = $"{start.Date:MMM d} – {end.Date:MMM d, yyyy}", MethodDescription = description.Text ?? "", MethodId = selected?.Id }; await _service.SaveWeeklyMethodAsync(item); if (selected != null) await _service.CreateSnapshotAsync(item.Id, selected.Id); await RefreshAsync(); }; _body.Children.Add(methodPicker); _body.Children.Add(description); _body.Children.Add(save);
    }
    private async Task ShowSnapshotAsync(int weekId, string name) { var snapshot = await _service.GetSnapshotAsync(weekId); if (snapshot == null) return; var text = $"{name} v{snapshot.Value.Method.Version}\n\n" + string.Join("\n\n", snapshot.Value.Stages.OrderBy(x => x.Position).Select(x => $"{x.Position + 1}. {x.StageName}\n{x.Instructions}\n{x.InputCount?.ToString() ?? "—"} → {x.OutputCount?.ToString() ?? "—"}; generations: {x.GenerationAllowance?.ToString() ?? "—"}")); await DisplayAlert("Method Snapshot", text, "OK"); }

    private async Task BuildMethodsAsync()
    {
        var methods = await _service.GetMethodsAsync(_auth.CurrentUsername);
        foreach (var method in methods)
        {
            var stages = await _service.GetStagesAsync(method.Id); var stack = new VerticalStackLayout { Spacing = 5 }; stack.Children.Add(new Label { Text = $"{method.Name} v{method.Version}", FontSize = 18, FontAttributes = FontAttributes.Bold }); stack.Children.Add(new Label { Text = method.Description }); stack.Children.Add(new Label { Text = $"{stages.Count} stage(s)" }); var actions = new HorizontalStackLayout { Spacing = 6 };
            var view = new Button { Text = "View Stages" }; view.Clicked += async (_, _) => { _expandedMethod = _expandedMethod == method.Id ? null : method.Id; await RefreshAsync(); }; var edit = new Button { Text = "Edit" }; edit.Clicked += async (_, _) => await EditMethodAsync(method); var archive = new Button { Text = "Archive" }; archive.Clicked += async (_, _) => { await _service.ArchiveMethodAsync(method.Id); await RefreshAsync(); }; actions.Children.Add(view); actions.Children.Add(edit); actions.Children.Add(archive); stack.Children.Add(actions); if (_expandedMethod == method.Id) await AddStagePipelineAsync(stack, method, stages); _body.Children.Add(new Frame { Padding = 12, BackgroundColor = Colors.White, Content = stack });
        }
        _body.Children.Add(new Label { Text = "New Method", FontSize = 20, FontAttributes = FontAttributes.Bold }); var name = new Entry { Placeholder = "Method name" }; var description = new Editor { Placeholder = "Describe the method...", HeightRequest = 100 }; var save = new Button { Text = "Save Method" }; save.Clicked += async (_, _) => { if (string.IsNullOrWhiteSpace(name.Text)) return; await _service.SaveMethodAsync(new ProductionMethod { Username = _auth.CurrentUsername, Name = name.Text.Trim(), Description = description.Text ?? "", Version = 1 }); await RefreshAsync(); }; _body.Children.Add(name); _body.Children.Add(description); _body.Children.Add(save);
    }
    private async Task AddStagePipelineAsync(VerticalStackLayout stack, ProductionMethod method, List<ProductionMethodStage> stages)
    {
        for (var i = 0; i < stages.Count; i++) { var stage = stages[i]; var line = new VerticalStackLayout { Padding = 8, BackgroundColor = Color.FromArgb("#E3F2FD") }; line.Children.Add(new Label { Text = $"{stage.Position + 1}. {stage.StageName}", FontAttributes = FontAttributes.Bold }); line.Children.Add(new Label { Text = stage.Instructions }); line.Children.Add(new Label { Text = $"{stage.InputCount?.ToString() ?? "—"} → {stage.OutputCount?.ToString() ?? "—"}; allowance {stage.GenerationAllowance?.ToString() ?? "—"}" }); var actions = new HorizontalStackLayout { Spacing = 4 }; var edit = new Button { Text = "Edit", FontSize = 11 }; edit.Clicked += async (_, _) => await EditStageAsync(stage); var del = new Button { Text = "Delete", FontSize = 11 }; del.Clicked += async (_, _) => { await _service.DeleteStageAsync(stage.Id); await RefreshAsync(); }; var up = new Button { Text = "↑", FontSize = 11, IsEnabled = i > 0 }; up.Clicked += async (_, _) => { (stages[i - 1].Position, stage.Position) = (stage.Position, stages[i - 1].Position); await _service.ReorderStagesAsync(stages.OrderBy(x => x.Position).ToList()); await RefreshAsync(); }; var down = new Button { Text = "↓", FontSize = 11, IsEnabled = i < stages.Count - 1 }; down.Clicked += async (_, _) => { (stages[i + 1].Position, stage.Position) = (stage.Position, stages[i + 1].Position); await _service.ReorderStagesAsync(stages.OrderBy(x => x.Position).ToList()); await RefreshAsync(); }; actions.Children.Add(edit); actions.Children.Add(del); actions.Children.Add(up); actions.Children.Add(down); line.Children.Add(actions); stack.Children.Add(line); if (i < stages.Count - 1) stack.Children.Add(new Label { Text = "↓", HorizontalOptions = LayoutOptions.Center }); }
        var stageName = new Entry { Placeholder = "Stage name" }; var instructions = new Editor { Placeholder = "Instructions", HeightRequest = 70 }; var input = new Entry { Placeholder = "Input count", Keyboard = Keyboard.Numeric }; var output = new Entry { Placeholder = "Output count", Keyboard = Keyboard.Numeric }; var allowance = new Entry { Placeholder = "Generation allowance", Keyboard = Keyboard.Numeric }; var save = new Button { Text = "Add Stage" }; save.Clicked += async (_, _) => { if (string.IsNullOrWhiteSpace(stageName.Text)) return; await _service.SaveStageAsync(new ProductionMethodStage { MethodId = method.Id, Position = stages.Count, StageName = stageName.Text.Trim(), Instructions = instructions.Text ?? "", InputCount = ParseInt(input.Text), OutputCount = ParseInt(output.Text), GenerationAllowance = ParseInt(allowance.Text) }); await RefreshAsync(); }; stack.Children.Add(new Label { Text = "Add Stage", FontAttributes = FontAttributes.Bold }); stack.Children.Add(stageName); stack.Children.Add(instructions); stack.Children.Add(input); stack.Children.Add(output); stack.Children.Add(allowance); stack.Children.Add(save);
    }
    private async Task EditMethodAsync(ProductionMethod method) { var name = await DisplayPromptAsync("Edit method", "Name", initialValue: method.Name); if (name == null) return; var description = await DisplayPromptAsync("Edit method", "Description", initialValue: method.Description); if (description == null) return; method.Name = name.Trim(); method.Description = description; await _service.SaveMethodAsync(method); await RefreshAsync(); }
    private async Task EditStageAsync(ProductionMethodStage stage) { var name = await DisplayPromptAsync("Edit stage", "Stage name", initialValue: stage.StageName); if (name == null) return; var instructions = await DisplayPromptAsync("Edit stage", "Instructions", initialValue: stage.Instructions); if (instructions == null) return; stage.StageName = name; stage.Instructions = instructions; await _service.SaveStageAsync(stage); await RefreshAsync(); }
    private static int? ParseInt(string? value) => int.TryParse(value, out var n) ? n : null;

    private async Task BuildClipsAsync()
    {
        var username = _auth.CurrentUsername; var weeks = await _service.GetActiveWeeklyMethodsAsync(username); var picker = new Picker { Title = "All Weeks", ItemsSource = new[] { "All Weeks" }.Concat(weeks.Select(x => x.WeekLabel)).ToList(), SelectedIndex = 0 }; picker.SelectedIndexChanged += async (_, _) => { _week = picker.SelectedIndex <= 0 ? null : weeks[picker.SelectedIndex - 1].Id; await RefreshAsync(); }; _body.Children.Add(picker); var search = new Entry { Placeholder = "Search hypothesis" }; _body.Children.Add(search); var add = new Button { Text = "+ Add Clip" }; add.Clicked += async (_, _) => { await _service.SaveClipAsync(new ClipExperiment { Username = username, WeeklyMethodExperimentId = _week }); await RefreshAsync(); }; _body.Children.Add(add);
        var clips = await _service.GetClipsAsync(username, _week); foreach (var clip in clips) { var card = new Frame { Padding = 10, BackgroundColor = Colors.White }; var stack = new VerticalStackLayout { Spacing = 5 }; stack.Children.Add(new Label { Text = string.IsNullOrWhiteSpace(clip.Hypothesis) ? "(Hypothesis required)" : clip.Hypothesis, FontAttributes = FontAttributes.Bold }); stack.Children.Add(new Label { Text = $"{clip.VariableTested} · {clip.PostedDate:yyyy-MM-dd} · {clip.Retention10s?.ToString("0.#") ?? "—"}/{clip.Retention20s?.ToString("0.#") ?? "—"}/{clip.Retention30s?.ToString("0.#") ?? "—"}" }); var edit = new Button { Text = "Edit" }; edit.Clicked += async (_, _) => await EditClipAsync(clip); var del = new Button { Text = "Delete" }; del.Clicked += async (_, _) => { await _service.DeleteClipAsync(clip.Id); await RefreshAsync(); }; stack.Children.Add(new HorizontalStackLayout { Children = { edit, del } }); card.Content = stack; _body.Children.Add(card); }
    }
    private async Task EditClipAsync(ClipExperiment clip) { var h = await DisplayPromptAsync("Clip", "Hypothesis", initialValue: clip.Hypothesis); if (h == null) return; clip.Hypothesis = h; clip.VariableTested = await DisplayPromptAsync("Clip", "Variable tested", initialValue: clip.VariableTested) ?? clip.VariableTested; clip.ControlConstant = await DisplayPromptAsync("Clip", "Control / constant", initialValue: clip.ControlConstant) ?? clip.ControlConstant; clip.GenerationMethodVersion = await DisplayPromptAsync("Clip", "Generation method/version", initialValue: clip.GenerationMethodVersion) ?? clip.GenerationMethodVersion; clip.Platform = await DisplayPromptAsync("Clip", "Platform", initialValue: clip.Platform) ?? clip.Platform; clip.Notes = await DisplayPromptAsync("Clip", "Notes", initialValue: clip.Notes) ?? clip.Notes; await _service.SaveClipAsync(clip); await RefreshAsync(); }
    private async Task BuildStatsAsync() { var label = new Label { Text = $"Threshold: {_threshold:0}%" }; var slider = new Slider { Minimum = 0, Maximum = 100, Value = _threshold }; slider.ValueChanged += async (_, e) => { _threshold = e.NewValue; label.Text = $"Threshold: {_threshold:0}%"; await RefreshAsync(); }; _body.Children.Add(label); _body.Children.Add(slider); var stats = await _service.GetComparisonStatsAsync(_auth.CurrentUsername, null, _threshold); _body.Children.Add(new Label { Text = $"Overall\nAvg: {stats.AverageRetention10s:0.#}/{stats.AverageRetention20s:0.#}/{stats.AverageRetention30s:0.#}\nMedian: {stats.MedianRetention10s:0.#}/{stats.MedianRetention20s:0.#}/{stats.MedianRetention30s:0.#}\nBest: {stats.BestRetention10s:0.#}/{stats.BestRetention20s:0.#}/{stats.BestRetention30s:0.#}\nAbove threshold: {stats.PercentageExceedingThreshold:0.#}% · Generations/clip: {stats.VideoGenerationsPerPublishedClip:0.##}" }); foreach (var hypothesis in await _service.GetHypothesisStatsAsync(_auth.CurrentUsername)) _body.Children.Add(new Label { Text = $"{hypothesis.Hypothesis}: {hypothesis.AverageRetention10s:0.#}/{hypothesis.AverageRetention20s:0.#}/{hypothesis.AverageRetention30s:0.#} ({hypothesis.Count})" }); }

    private async Task BuildExecutionAsync()
    {
        var weeks = await _service.GetActiveWeeklyMethodsAsync(_auth.CurrentUsername); var picker = new Picker { Title = "Choose a week", ItemsSource = weeks.Select(x => x.WeekLabel).ToList(), SelectedIndex = weeks.Count > 0 ? 0 : -1 }; _body.Children.Add(picker); if (weeks.Count == 0) { _body.Children.Add(new Label { Text = "No active weeks." }); return; } _week ??= weeks[0].Id; picker.SelectedIndexChanged += async (_, _) => { _week = weeks[picker.SelectedIndex].Id; await RefreshAsync(); };
        var week = weeks.FirstOrDefault(x => x.Id == _week) ?? weeks[0]; var snapshot = await _service.GetSnapshotAsync(week.Id); if (snapshot == null) { _body.Children.Add(new Label { Text = "No method assigned to this week" } ); return; } var stages = snapshot.Value.Stages.OrderBy(x => x.Position).ToList(); if (stages.Count == 0) { _body.Children.Add(new Label { Text = "This method has no stages." }); return; } var current = _executionStages.TryGetValue(week.Id, out var n) ? Math.Min(n, stages.Count - 1) : 0; _executionStages[week.Id] = current; var stage = stages[current]; _body.Children.Add(new Label { Text = $"Stage {current + 1} of {stages.Count}", FontAttributes = FontAttributes.Bold }); _body.Children.Add(new Frame { Padding = 12, BackgroundColor = Color.FromArgb("#E3F2FD"), Content = new VerticalStackLayout { Children = { new Label { Text = stage.StageName, FontSize = 19, FontAttributes = FontAttributes.Bold }, new Label { Text = stage.Instructions }, new Label { Text = $"Planned input/output: {stage.InputCount?.ToString() ?? "—"}/{stage.OutputCount?.ToString() ?? "—"}; generations: {stage.GenerationAllowance?.ToString() ?? "—"}" } } } }); var actualInput = new Entry { Placeholder = "Actual input", Keyboard = Keyboard.Numeric }; var actualOutput = new Entry { Placeholder = "Actual output", Keyboard = Keyboard.Numeric }; var actualGenerations = new Entry { Placeholder = "Actual generations", Keyboard = Keyboard.Numeric }; _body.Children.Add(actualInput); _body.Children.Add(actualOutput); _body.Children.Add(actualGenerations); var complete = new Button { Text = current == stages.Count - 1 ? "Stage Complete" : "Stage Complete → Next" }; complete.Clicked += async (_, _) => { if (current < stages.Count - 1) _executionStages[week.Id] = current + 1; else await LogExecutionClipAsync(week, snapshot.Value.Method.Version); await RefreshAsync(); }; _body.Children.Add(complete);
    }
    private async Task LogExecutionClipAsync(WeeklyMethodExperiment week, int version) { var hypothesis = await DisplayPromptAsync("Log Clip", "Hypothesis", placeholder: "What did this clip test?"); if (hypothesis == null) return; await _service.SaveClipAsync(new ClipExperiment { Username = _auth.CurrentUsername, WeeklyMethodExperimentId = week.Id, GenerationMethodVersion = $"v{version}", Hypothesis = hypothesis }); await DisplayAlert("Clip logged", "The clip was added to this week.", "OK"); }
}
