using Bannister.Models;
using Bannister.Services;

namespace Bannister.Views;

public class VideoGenExperimentPage : ContentPage
{
    readonly VideoGenExperimentService _service; readonly AuthService _auth;
    VerticalStackLayout _body = null!; int _tab; int? _week; double _threshold = 50;
    public VideoGenExperimentPage(VideoGenExperimentService service, AuthService auth) { _service = service; _auth = auth; Title = "Video Generation Experiments"; BackgroundColor = Color.FromArgb("#F5F5F5"); BuildUI(); }
    protected override async void OnAppearing() { base.OnAppearing(); await RefreshAsync(); }
    void BuildUI() { var root = new VerticalStackLayout { Padding = 16, Spacing = 10 }; root.Children.Add(new Label { Text = "Video Generation Experiments", FontSize = 24, FontAttributes = FontAttributes.Bold }); var tabs = new HorizontalStackLayout { Spacing = 6 }; foreach (var t in new[]{"Weekly Methods","Clips","Stats"}) { var b = new Button { Text=t, FontSize=12 }; int i = Array.IndexOf(new[]{"Weekly Methods","Clips","Stats"},t); b.Clicked += async (_,_)=>{_tab=i; await RefreshAsync();}; tabs.Children.Add(b); } root.Children.Add(tabs); _body = new VerticalStackLayout { Spacing=10 }; root.Children.Add(new ScrollView { Content=_body }); Content = root; }
    async Task RefreshAsync() { _body.Children.Clear(); if (_tab==0) await BuildWeeksAsync(); else if (_tab==1) await BuildClipsAsync(); else await BuildStatsAsync(); }
    async Task BuildWeeksAsync() { var user=_auth.CurrentUsername; var weeks=await _service.GetActiveWeeklyMethodsAsync(user); foreach(var w in weeks) { var clips=await _service.GetClipsAsync(user,w.Id); var s=await _service.GetComparisonStatsAsync(user,w.Id); var card=new Frame { Padding=12, BackgroundColor=Colors.White, Content=new VerticalStackLayout { Children={new Label{Text=w.WeekLabel,FontAttributes=FontAttributes.Bold,FontSize=18},new Label{Text=w.MethodDescription,MaxLines=3},new Label{Text=$"{clips.Count} clips · {clips.Count(x=>x.PostedDate.HasValue)} posted · Avg {s.AverageRetention10s:0.#}/{s.AverageRetention20s:0.#}/{s.AverageRetention30s:0.#}"}}}}; var row=(VerticalStackLayout)((Frame)card).Content; var buttons=new HorizontalStackLayout{Spacing=6}; var open=new Button{Text="View Clips"}; open.Clicked+=async(_,_)=>{_week=w.Id;_tab=1;await RefreshAsync();}; var edit=new Button{Text="Edit"}; edit.Clicked+=async(_,_)=>{var d=await DisplayPromptAsync("Method description","Edit description",initialValue:w.MethodDescription);if(d!=null){w.MethodDescription=d;await _service.SaveWeeklyMethodAsync(w);await RefreshAsync();}}; var arch=new Button{Text="Archive"}; arch.Clicked+=async(_,_)=>{await _service.ArchiveWeeklyMethodAsync(w.Id);await RefreshAsync();}; buttons.Children.Add(open);buttons.Children.Add(edit);buttons.Children.Add(arch);row.Children.Add(buttons); _body.Children.Add(card); } var label=new Label{Text="Add Week",FontSize=20,FontAttributes=FontAttributes.Bold}; _body.Children.Add(label); var week=new Entry{Placeholder="Week label"};var desc=new Editor{Placeholder="Describe the production method...",HeightRequest=110};var save=new Button{Text="Save Week"};save.Clicked+=async(_,_)=>{if(string.IsNullOrWhiteSpace(week.Text))return;await _service.SaveWeeklyMethodAsync(new WeeklyMethodExperiment{Username=user,WeekLabel=week.Text.Trim(),MethodDescription=desc.Text??""});await RefreshAsync();};_body.Children.Add(week);_body.Children.Add(desc);_body.Children.Add(save); }
    async Task BuildClipsAsync() { var user=_auth.CurrentUsername; var weeks=await _service.GetActiveWeeklyMethodsAsync(user); var picker=new Picker{Title="All Weeks",ItemsSource=(new[]{"All Weeks"}).Concat(weeks.Select(x=>x.WeekLabel)).ToList()}; picker.SelectedIndex=0; picker.SelectedIndexChanged+=async(_,_)=>{_week=picker.SelectedIndex<=0?null:weeks[picker.SelectedIndex-1].Id;await RefreshAsync();}; var search=new Entry{Placeholder="Search hypothesis"}; _body.Children.Add(picker);_body.Children.Add(search); var add=new Button{Text="+ Add Clip"};add.Clicked+=async(_,_)=>{var c=new ClipExperiment{Username=user,WeeklyMethodExperimentId=_week};await _service.SaveClipAsync(c);await RefreshAsync();};_body.Children.Add(add);var clips=await _service.GetClipsAsync(user,_week); foreach(var c in clips) { var card=new Frame{Padding=10,BackgroundColor=Colors.White};var stack=new VerticalStackLayout{Spacing=5};stack.Children.Add(new Label{Text=string.IsNullOrWhiteSpace(c.Hypothesis)?"(Hypothesis required)":c.Hypothesis,FontAttributes=FontAttributes.Bold});stack.Children.Add(new Label{Text=$"{c.VariableTested} · {c.PostedDate:yyyy-MM-dd} · {c.Retention10s?.ToString("0.#") ?? "—"}/{c.Retention20s?.ToString("0.#") ?? "—"}/{c.Retention30s?.ToString("0.#") ?? "—"}"});var edit=new Button{Text="Edit"};edit.Clicked+=async(_,_)=>await EditClipAsync(c,weeks);var del=new Button{Text="Delete"};del.Clicked+=async(_,_)=>{await _service.DeleteClipAsync(c.Id);await RefreshAsync();};stack.Children.Add(new HorizontalStackLayout{Children={edit,del}});card.Content=stack;_body.Children.Add(card);} }
    async Task EditClipAsync(ClipExperiment c,List<WeeklyMethodExperiment> weeks) { var h=await DisplayPromptAsync("Hypothesis","Hypothesis",initialValue:c.Hypothesis);if(h==null)return;c.Hypothesis=h;c.VariableTested=await DisplayPromptAsync("Variable","Variable tested",initialValue:c.VariableTested)??c.VariableTested;c.ControlConstant=await DisplayPromptAsync("Control","Control / constant",initialValue:c.ControlConstant)??c.ControlConstant;c.GenerationMethodVersion=await DisplayPromptAsync("Method","Generation method/version",initialValue:c.GenerationMethodVersion)??c.GenerationMethodVersion;c.Platform=await DisplayPromptAsync("Platform","Platform",initialValue:c.Platform)??c.Platform;c.Notes=await DisplayPromptAsync("Notes","Notes",initialValue:c.Notes)??c.Notes;await _service.SaveClipAsync(c);await RefreshAsync(); }
    async Task BuildStatsAsync() { var user=_auth.CurrentUsername; var slider=new Slider{Minimum=0,Maximum=100,Value=_threshold};var value=new Label{Text=$"Threshold: {_threshold:0}%"};slider.ValueChanged+=async(_,e)=>{_threshold=e.NewValue;value.Text=$"Threshold: {_threshold:0}%";await RefreshAsync();};_body.Children.Add(value);_body.Children.Add(slider);var s=await _service.GetComparisonStatsAsync(user,null,_threshold);_body.Children.Add(new Label{Text=$"Overall\nAvg: {s.AverageRetention10s:0.#}/{s.AverageRetention20s:0.#}/{s.AverageRetention30s:0.#}\nMedian: {s.MedianRetention10s:0.#}/{s.MedianRetention20s:0.#}/{s.MedianRetention30s:0.#}\nBest: {s.BestRetention10s:0.#}/{s.BestRetention20s:0.#}/{s.BestRetention30s:0.#}\nAbove threshold: {s.PercentageExceedingThreshold:0.#}% · Generations/clip: {s.VideoGenerationsPerPublishedClip:0.##}"});foreach(var h in await _service.GetHypothesisStatsAsync(user))_body.Children.Add(new Label{Text=$"{h.Hypothesis}: {h.AverageRetention10s:0.#}/{h.AverageRetention20s:0.#}/{h.AverageRetention30s:0.#} ({h.Count})"}); }
}
